# Generated by Django 3.0.5 on 2020-04-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Golang', max_length=400)),
                ('author', models.CharField(default='MIT', max_length=400)),
                ('image_ref', models.CharField(default='../images/default.jpg', max_length=400)),
                ('description', models.CharField(default='Golang language course from MIT university', max_length=1500)),
                ('price', models.FloatField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_ref', models.CharField(default='../images/default.jpg', max_length=400)),
                ('description', models.CharField(default='Some course', max_length=400)),
                ('year', models.CharField(default=2001, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_ref', models.CharField(default='../images/default.jpg', max_length=400)),
                ('degree', models.CharField(default='Magister', max_length=400)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('university', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.University')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='John', max_length=400)),
                ('description', models.CharField(default='Some course', max_length=400)),
                ('liked', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Teacher')),
            ],
        ),
    ]
